#!/usr/bin/python1.5

import CORBA
import sys,string,time
import Test

orb = CORBA.ORB_init(sys.argv, CORBA.ORB_ID)
ior = sys.argv[1]
o = orb.string_to_object(ior)

print o
start=time.time()
for x in range(1,16000):
  y=o.echoString('foo')
print time.time()-start

start=time.time()
for x in range(1,16000):
  o.loseString('foo')
print time.time()-start

