#ifndef _CUEFADER_IDL_
#define _CUEFADER_IDL_

#include "Fader.idl"

module LB
{
  interface CueFader : Fader
  {
    void setCues (in Cue startcue, in Cue endcue);

    void setAttributes (in AttrList attr);
    void clear ();
  };

};

#endif /* _CUEFADER_IDL_ */
