#ifndef _FADER_IDL_
#define _FADER_IDL_

#include "types.idl"

module LB
{
  interface Fader : EventSender
  {
    readonly attribute string name;

    void run (in double level, in double time);
    void addRunListener (in EventListener l);
    void removeRunListener (in EventListener l);

    void stop ();
    void addStopListener (in EventListener l);
    void removeStopListener (in EventListener l);

    void setLevel (in double level);
    double getLevel ();
    void addLevelListener (in EventListener l);
    void removeLevelListener (in EventListener l);

    void addCompleteListener (in EventListener l);
    void removeCompleteListener (in EventListener l);

    void addSourceListener (in EventListener l);
    void removeSourceListener (in EventListener l);

    boolean isRunning ();
    // wait for
  };
};

#endif /* _FADER_IDL_ */
