#ifndef _FADER_IDL_
#define _FADER_IDL_

#include "types.idl"

module LB
{
  interface Fader : EventSender
  {
    readonly attribute string name;

    void run (in double level, in double time);
    long addRunListener (in EventListener l);
    void removeRunListener (in long id);

    void stop ();
    long addStopListener (in EventListener l);
    void removeStopListener (in long id);

    void setLevel (in double level);
    double getLevel ();
    long addLevelListener (in EventListener l);
    void removeLevelListener (in long id);

    long addCompleteListener (in EventListener l);
    void removeCompleteListener (in long id);

    long addSourceListener (in EventListener l);
    void removeSourceListener (in long id);

    boolean isRunning ();
    // wait for
  };
};

#endif /* _FADER_IDL_ */
