#ifndef _LIGHTBOARD_IDL_
#define _LIGHTBOARD_IDL_

#include "types.idl"
#include "Instrument.idl"
#include "Fader.idl"
#include "CueFader.idl"
#include "CrossFader.idl"
#include "LevelFader.idl"
#include "Dimmer.idl"

module LB
{
  interface Lightboard
  {
    readonly attribute unsigned long dimmerRange;
    readonly attribute string name;

    long createInstrument (in string show, 
			   in string name, 
			   in string driver,
			   in ArgList arguments);
    long createLevelFader (in string show, in string name);
    long createCueFader (in string show, in string name);
    long createCrossFader (in string show, in string name);


    /*** Intra-core use only ***/
    /* Don't call these from clients, only cores */

    void addEvent(in Event evt);
    void addDriver(in string name, 
		   in InstrumentFactory fact);    
  };
};

#endif /* _LIGHTBOARD_IDL_ */
