#ifndef _TYPES_IDL_
#define _TYPES_IDL_

module LB
{
  interface Instrument;

  enum AttrType
    {
      attr_level,     // .01 percent
      attr_target,    // millimeter, millimeter, millimeter
      attr_focus,     // ?
      attr_color,     // .01 percent r, g, b
      attr_gobo       // ?
    };

  struct AttrValue
  {
    AttrType attr;
    sequence<double> value;
  };

  struct InstAttrs
  {
    string name;
    Instrument inst;
    sequence<AttrValue> attrs;
  };

  struct Cue
  {
    string name;
    sequence<InstAttrs> ins;
  };

  typedef sequence<AttrType> AttrList;

  enum EventType
    {
      event_instrument_level,
      event_instrument_target,

      event_fader_level,
      event_fader_run,
      event_fader_stop,
      event_fader_complete,
      event_fader_source
    };
 
  struct Event
  {
    EventType type;
    Object source;
    sequence<double> value;
  };

  interface EventListener
  {
    void receiveEvent(in Event evt);
  };

  interface EventSender
  {
    void sendEvent(in Event evt);
  };

};

#endif /* _TYPES_IDL_ */
