#ifndef _TYPES_IDL_
#define _TYPES_IDL_

module LB
{
  interface Instrument;

  enum AttrType
    {
      attr_level,     // percent
      attr_target,    // 
      attr_focus,     // 
      attr_color,     // r, g, b percent
      attr_gobo,      // 
      attr_gobo_rpm   // rpm +,-,0
    };

  struct AttrValue
  {
    AttrType attr;
    sequence<double> value;
  };

  struct InstAttrs
  {
    string name;
    Instrument inst;
    sequence<AttrValue> attrs;
  };

  struct Cue
  {
    string name;
    sequence<InstAttrs> ins;
  };

  typedef sequence<AttrType> AttrList;

  struct Argument
  {
    string name;
    string value;
  };

  typedef sequence<Argument> ArgList;

  enum EventType
    {
      event_instrument_level,
      event_instrument_target,
      event_instrument_gobo_rpm,

      event_fader_level,
      event_fader_run,
      event_fader_stop,
      event_fader_complete,
      event_fader_source
    };
 
  struct Event
  {
    EventType type;
    Object source;
    sequence<double> value;
  };

  interface EventListener
  {
    void receiveEvent(in Event evt);
  };

  interface EventSender
  {
    void sendEvent(in Event evt);
  };

};

#endif /* _TYPES_IDL_ */
