#ifndef _CUEFADER_IDL_
#define _CUEFADER_IDL_

#include "Fader.idl"

module LB
{
  interface CueFader : Fader
  {
    void setStartCue (in Cue incue);
    void setEndCue (in Cue incue);
    void setAttributes (in AttrList attr);
    void clear ();
  };

};

#endif /* _CUEFADER_IDL_ */
