#ifndef _DIMMER_IDL_
#define _DIMMER_IDL_

#include "types.idl"

module LB
{
  interface Dimmer
  {
    readonly attribute string name;
    readonly attribute string device;
    readonly attribute long number;

    void setLevel (in double level);
    double getLevel ();
    void setValue (in long value);
    long getValue ();
  };
  
};


#endif /* _DIMMER_IDL_ */
