#ifndef _FADER_IDL_
#define _FADER_IDL_

#include "types.idl"

module LB
{
  interface FaderLevelListener
  {
    void levelChanged(in Event evt);
  };
  interface FaderRunListener
  {
    void runStarted(in Event evt);
  };
  interface FaderStopListener
  {
    void runStopped(in Event evt);
  };
  interface FaderCompleteListener
  {
    void runCompleted(in Event evt);
  };
  interface Fader
  {
    readonly attribute string name;

    void run (in double level, in double time);
    void addRunListener (in FaderRunListener l);
    void removeRunListener (in FaderRunListener l);

    void stop ();
    void addStopListener (in FaderStopListener l);
    void removeStopListener (in FaderStopListener l);

    void setLevel (in double level);
    void addLevelListener (in FaderLevelListener l);
    void removeLevelListener (in FaderLevelListener l);

    void addCompleteListener (in FaderCompleteListener l);
    void removeCompleteListener (in FaderCompleteListener l);

    boolean isRunning ();
    // wait for



    /*** Intra-core use only ***/

    /* Don't call these from clients, only other cores */

    void doFireLevelEvent(in Event evt);
    void doFireRunEvent(in Event evt);
    void doFireStopEvent(in Event evt);
    void doFireCompleteEvent(in Event evt);
  };

};

#endif /* _FADER_IDL_ */
