#ifndef _INSTRUMENT_IDL_
#define _INSTRUMENT_IDL_

#include "types.idl"

module LB
{
  interface Instrument
  {
    readonly attribute string name;

    AttrList getAttributes();

    void setLevel (in double level); /* percent */
    double getLevel ();

    void setTarget(in double x, in double y, in double z);
    void getTarget(out double x, out double y, out double z);
  };
  
};


#endif /* _INSTRUMENT_IDL_ */
