#ifndef _LIGHTBOARD_IDL_
#define _LIGHTBOARD_IDL_

#include "types.idl"
#include "Instrument.idl"
#include "MovingInstrument.idl"
#include "Fader.idl"
#include "CueFader.idl"
#include "Dimmer.idl"

module LB
{
  interface Lightboard
  {
    readonly attribute unsigned long dimmerRange;

    Instrument getInstrument (in string name);
    void putInstrument (in Instrument ins);

    Fader getFader (in string name);
    void putFader (in Fader fadr);

    Dimmer getDimmer (in string name);
    void putDimmer (in Dimmer dimr);
  };
};

#endif /* _LIGHTBOARD_IDL_ */
