#ifndef _TYPES_IDL_
#define _TYPES_IDL_

module LB
{
  enum AttrType
    {
      attr_level,     // .01 percent
      attr_target,    // millimeter, millimeter, millimeter
      attr_focus,     // ?
      attr_color,     // .01 percent r, g, b
      attr_gobo       // ?
    };

  struct AttrValue
  {
    AttrType attr;
    sequence<double> value;
  };

  struct InstAttrs
  {
    string name;
    sequence<AttrValue> attrs;
  };

  struct Cue
  {
    string name;
    sequence<InstAttrs> ins;
  };

  typedef sequence<AttrType> AttrList;
    
};

#endif /* _TYPES_IDL_ */
